services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-ci
    user: root
    privileged: true
    ports:
      - "8081:8080"
    environment:
      DOCKER_HOST: npipe:////./pipe/docker_engine
      JENKINS_HOME_HOST: ./jenkins_home
      TZ: Etc/GMT+3
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    restart: unless-stopped